### ISSUE TITLE
Cannot able to install it in Ubuntu 20.01

### ISSUE THREAD

**Issue by menporulporiayalan** [TheWeirdDev/Bluetooth_Headset_Battery_Level#27]
I tried to install it in my system which has ubuntu 20.01. But I got error as below. 

```
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-Jio3Nv/bluetooth-battery/setup.py'"'"'; __file__='"'"'/tmp/pip-install-Jio3Nv/bluetooth-battery/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-THeq9Q
         cwd: /tmp/pip-install-Jio3Nv/bluetooth-battery/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Jio3Nv/bluetooth-battery/setup.py", line 6, in <module>
        with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by TheWeirdDev** [comment]
Try using `pip3` instead of pip

**Comment by superbonaci** [comment]
Yes add to README

**Comment by mirsahib** [comment]
same error using Ubuntu 18.04 even with pip3 here is my log

```
Collecting bluetooth_battery
Collecting PyBluez (from bluetooth_battery)
  Using cached https://files.pythonhosted.org/packages/08/9f/e9d93b266d2d1ea988780a52a696073ba0a65df65a532165fdf6ff90d0ed/PyBluez-0.23.tar.gz
Building wheels for collected packages: PyBluez
  Running setup.py bdist_wheel for PyBluez: started
  Running setup.py bdist_wheel for PyBluez: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vkkpbeie/PyBluez/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpb0sku2bjpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/bluetooth
  copying bluetooth/ble.py -> build/lib.linux-x86_64-3.6/bluetooth
  copying bluetooth/widcomm.py -> build/lib.linux-x86_64-3.6/bluetooth
  copying bluetooth/macos.py -> build/lib.linux-x86_64-3.6/bluetooth
  copying bluetooth/__init__.py -> build/lib.linux-x86_64-3.6/bluetooth
  copying bluetooth/msbt.py -> build/lib.linux-x86_64-3.6/bluetooth
  copying bluetooth/btcommon.py -> build/lib.linux-x86_64-3.6/bluetooth
  copying bluetooth/bluez.py -> build/lib.linux-x86_64-3.6/bluetooth
  Fixing build/lib.linux-x86_64-3.6/bluetooth/ble.py build/lib.linux-x86_64-3.6/bluetooth/widcomm.py build/lib.linux-x86_64-3.6/bluetooth/macos.py build/lib.linux-x86_64-3.6/bluetooth/__init__.py build/lib.linux-x86_64-3.6/bluetooth/msbt.py build/lib.linux-x86_64-3.6/bluetooth/btcommon.py build/lib.linux-x86_64-3.6/bluetooth/bluez.py
  Skipping optional fixer: buffer
  Skipping optional fixer: idioms
  Skipping optional fixer: set_literal
  Skipping optional fixer: ws_comma
  Fixing build/lib.linux-x86_64-3.6/bluetooth/ble.py build/lib.linux-x86_64-3.6/bluetooth/widcomm.py build/lib.linux-x86_64-3.6/bluetooth/macos.py build/lib.linux-x86_64-3.6/bluetooth/__init__.py build/lib.linux-x86_64-3.6/bluetooth/msbt.py build/lib.linux-x86_64-3.6/bluetooth/btcommon.py build/lib.linux-x86_64-3.6/bluetooth/bluez.py
  Skipping optional fixer: buffer
  Skipping optional fixer: idioms
  Skipping optional fixer: set_literal
  Skipping optional fixer: ws_comma
  running build_ext
  building 'bluetooth._bluetooth' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/bluez
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I./port3 -I/usr/include/python3.6m -c bluez/btmodule.c -o build/temp.linux-x86_64-3.6/bluez/btmodule.o
  In file included from bluez/btmodule.c:20:0:
  bluez/btmodule.h:5:10: fatal error: bluetooth/bluetooth.h: No such file or directory
   #include <bluetooth/bluetooth.h>
            ^~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Running setup.py clean for PyBluez
Failed to build PyBluez
Installing collected packages: PyBluez, bluetooth-battery
  Running setup.py install for PyBluez: started
    Running setup.py install for PyBluez: finished with status 'error'
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vkkpbeie/PyBluez/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pyqdfdzw-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/bluetooth
    copying bluetooth/ble.py -> build/lib.linux-x86_64-3.6/bluetooth
    copying bluetooth/widcomm.py -> build/lib.linux-x86_64-3.6/bluetooth
    copying bluetooth/macos.py -> build/lib.linux-x86_64-3.6/bluetooth
    copying bluetooth/__init__.py -> build/lib.linux-x86_64-3.6/bluetooth
    copying bluetooth/msbt.py -> build/lib.linux-x86_64-3.6/bluetooth
    copying bluetooth/btcommon.py -> build/lib.linux-x86_64-3.6/bluetooth
    copying bluetooth/bluez.py -> build/lib.linux-x86_64-3.6/bluetooth
    Fixing build/lib.linux-x86_64-3.6/bluetooth/ble.py build/lib.linux-x86_64-3.6/bluetooth/widcomm.py build/lib.linux-x86_64-3.6/bluetooth/macos.py build/lib.linux-x86_64-3.6/bluetooth/__init__.py build/lib.linux-x86_64-3.6/bluetooth/msbt.py build/lib.linux-x86_64-3.6/bluetooth/btcommon.py build/lib.linux-x86_64-3.6/bluetooth/bluez.py
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    Fixing build/lib.linux-x86_64-3.6/bluetooth/ble.py build/lib.linux-x86_64-3.6/bluetooth/widcomm.py build/lib.linux-x86_64-3.6/bluetooth/macos.py build/lib.linux-x86_64-3.6/bluetooth/__init__.py build/lib.linux-x86_64-3.6/bluetooth/msbt.py build/lib.linux-x86_64-3.6/bluetooth/btcommon.py build/lib.linux-x86_64-3.6/bluetooth/bluez.py
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running build_ext
    building 'bluetooth._bluetooth' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/bluez
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I./port3 -I/usr/include/python3.6m -c bluez/btmodule.c -o build/temp.linux-x86_64-3.6/bluez/btmodule.o
    In file included from bluez/btmodule.c:20:0:
    bluez/btmodule.h:5:10: fatal error: bluetooth/bluetooth.h: No such file or directory
     #include <bluetooth/bluetooth.h>
              ^~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
```

**Comment by TheWeirdDev** [comment]
@mirsahib You need to install `libbluetooth-dev`

`sudo apt install libbluetooth-dev`

**Comment by menporulporiayalan** [comment]
@TheWeirdDev  I installed `libbluetooth-dev` But still the error. 
```

sudo apt install libbluetooth-dev```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libbluetooth-dev is already the newest version (5.53-0ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 193 not upgraded.
```
```

`pip install bluetooth_battery

ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7iju8mxv/PyBluez/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7iju8mxv/PyBluez/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-wg07ggs_
       cwd: /tmp/pip-install-7iju8mxv/PyBluez/
  Complete output (34 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/bluetooth
  copying bluetooth/macos.py -> build/lib.linux-x86_64-3.7/bluetooth
  copying bluetooth/ble.py -> build/lib.linux-x86_64-3.7/bluetooth
  copying bluetooth/msbt.py -> build/lib.linux-x86_64-3.7/bluetooth
  copying bluetooth/widcomm.py -> build/lib.linux-x86_64-3.7/bluetooth
  copying bluetooth/bluez.py -> build/lib.linux-x86_64-3.7/bluetooth
  copying bluetooth/btcommon.py -> build/lib.linux-x86_64-3.7/bluetooth
  copying bluetooth/__init__.py -> build/lib.linux-x86_64-3.7/bluetooth
  Fixing build/lib.linux-x86_64-3.7/bluetooth/macos.py build/lib.linux-x86_64-3.7/bluetooth/ble.py build/lib.linux-x86_64-3.7/bluetooth/msbt.py build/lib.linux-x86_64-3.7/bluetooth/widcomm.py build/lib.linux-x86_64-3.7/bluetooth/bluez.py build/lib.linux-x86_64-3.7/bluetooth/btcommon.py build/lib.linux-x86_64-3.7/bluetooth/__init__.py
  Skipping optional fixer: buffer
  Skipping optional fixer: idioms
  Skipping optional fixer: set_literal
  Skipping optional fixer: ws_comma
  Fixing build/lib.linux-x86_64-3.7/bluetooth/macos.py build/lib.linux-x86_64-3.7/bluetooth/ble.py build/lib.linux-x86_64-3.7/bluetooth/msbt.py build/lib.linux-x86_64-3.7/bluetooth/widcomm.py build/lib.linux-x86_64-3.7/bluetooth/bluez.py build/lib.linux-x86_64-3.7/bluetooth/btcommon.py build/lib.linux-x86_64-3.7/bluetooth/__init__.py
  Skipping optional fixer: buffer
  Skipping optional fixer: idioms
  Skipping optional fixer: set_literal
  Skipping optional fixer: ws_comma
  running build_ext
  building 'bluetooth._bluetooth' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/bluez
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.7-04P6eK/python3.7-3.7.8=. -fstack-protector-strong -Wformat -Werror=format-security -g -fdebug-prefix-map=/build/python3.7-04P6eK/python3.7-3.7.8=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I./port3 -I/usr/include/python3.7m -c bluez/btmodule.c -o build/temp.linux-x86_64-3.7/bluez/btmodule.o
  In file included from bluez/btmodule.c:20:
  bluez/btmodule.h:4:10: fatal error: Python.h: No such file or directory
      4 | #include "Python.h"
        |          ^~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for PyBluez
  Running setup.py clean for PyBluez
Failed to build PyBluez
Installing collected packages: PyBluez, bluetooth-battery
    Running setup.py install for PyBluez ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7iju8mxv/PyBluez/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7iju8mxv/PyBluez/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ulmimsb8/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/emperoreby/.local/include/python3.7m/PyBluez
         cwd: /tmp/pip-install-7iju8mxv/PyBluez/
    Complete output (34 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/bluetooth
    copying bluetooth/macos.py -> build/lib.linux-x86_64-3.7/bluetooth
    copying bluetooth/ble.py -> build/lib.linux-x86_64-3.7/bluetooth
    copying bluetooth/msbt.py -> build/lib.linux-x86_64-3.7/bluetooth
    copying bluetooth/widcomm.py -> build/lib.linux-x86_64-3.7/bluetooth
    copying bluetooth/bluez.py -> build/lib.linux-x86_64-3.7/bluetooth
    copying bluetooth/btcommon.py -> build/lib.linux-x86_64-3.7/bluetooth
    copying bluetooth/__init__.py -> build/lib.linux-x86_64-3.7/bluetooth
    Fixing build/lib.linux-x86_64-3.7/bluetooth/macos.py build/lib.linux-x86_64-3.7/bluetooth/ble.py build/lib.linux-x86_64-3.7/bluetooth/msbt.py build/lib.linux-x86_64-3.7/bluetooth/widcomm.py build/lib.linux-x86_64-3.7/bluetooth/bluez.py build/lib.linux-x86_64-3.7/bluetooth/btcommon.py build/lib.linux-x86_64-3.7/bluetooth/__init__.py
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    Fixing build/lib.linux-x86_64-3.7/bluetooth/macos.py build/lib.linux-x86_64-3.7/bluetooth/ble.py build/lib.linux-x86_64-3.7/bluetooth/msbt.py build/lib.linux-x86_64-3.7/bluetooth/widcomm.py build/lib.linux-x86_64-3.7/bluetooth/bluez.py build/lib.linux-x86_64-3.7/bluetooth/btcommon.py build/lib.linux-x86_64-3.7/bluetooth/__init__.py
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running build_ext
    building 'bluetooth._bluetooth' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/bluez
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.7-04P6eK/python3.7-3.7.8=. -fstack-protector-strong -Wformat -Werror=format-security -g -fdebug-prefix-map=/build/python3.7-04P6eK/python3.7-3.7.8=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I./port3 -I/usr/include/python3.7m -c bluez/btmodule.c -o build/temp.linux-x86_64-3.7/bluez/btmodule.o
    In file included from bluez/btmodule.c:20:
    bluez/btmodule.h:4:10: fatal error: Python.h: No such file or directory
        4 | #include "Python.h"
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7iju8mxv/PyBluez/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7iju8mxv/PyBluez/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ulmimsb8/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/emperoreby/.local/include/python3.7m/PyBluez Check the logs for full command output.

`

**Comment by TheWeirdDev** [comment]
@menporulporiayalan  instead of pip3, try installing pybluez using apt. `python3-pybluez` or `python3-bluez` should be in ubuntu repositories.

**Comment by mirsahib** [comment]
@TheWeirdDev i am able to run this using the .py file but could run through pip install but my pip installation was successfull 
i get blutooth_battery command not found error (terminal)

**Comment by TheWeirdDev** [comment]
check your spelling, it's `bluetooth_battery` not blutooth_battery

**Comment by menporulporiayalan** [comment]
@TheWeirdDev  My issue solved Thanks!

**Comment by superbonaci** [comment]
@menporulporiayalan thanks for letting us know!

**Comment by laksh225** [comment]
Close #27
