### ISSUE TITLE
System reports syntax error

### ISSUE THREAD

**Issue by KelvinShadewing** [TheWeirdDev/Bluetooth_Headset_Battery_Level#39]
Installed using pip method.

```
$ bluetooth_battery 00:00:00:00:00:00
Traceback (most recent call last):
  File "/home/kelvin/.local/bin/bluetooth_battery", line 9, in <module>
    load_entry_point('bluetooth-battery==1.2.0', 'console_scripts', 'bluetooth_battery')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kelvin/.local/lib/python3.5/site-packages/bluetooth_battery/bluetooth_battery.py", line 59
    print(f"Battery level for {device} is {blevel}%")
                                                   ^
SyntaxError: invalid syntax
```

**Comment by TheWeirdDev** [comment]
You are probably using an old version of Python. Minimum version required for this script is Python 3.6.0

**Comment by KelvinShadewing** [comment]
It seems I have that as well as 2.7 installed. How do I make it run using Python3 instead?

**Comment by TheWeirdDev** [comment]
It should be using python 3 automatically. I suspect that you installed it using pip instead of pip3.

**Comment by TheWeirdDev** [comment]
Run this command in bash and check if it works:
```
python3 $(which bluetooth_battery)
```

**Comment by KelvinShadewing** [comment]
I have confirmed it was installed with pip3. The same error still appears with that command you posted. I even uninstalled and reinstalled.

**Comment by TheWeirdDev** [comment]
Please provide the output of this command:
```bash
python --version
```

Judging by the error log you posted, it seems like you are running python 3.5 but at least 3.6 is required

```
 File "/home/kelvin/.local/lib/python3.5/site-packages/bluetooth_battery/bluetooth_battery.py", line 59
    print(f"Battery level for {device} is {blevel}%")
```

**Comment by TheWeirdDev** [comment]
Closed due to the inactivity.
