### ISSUE TITLE
bluetooth.btcommon.BluetoothError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by manel00** [TheWeirdDev/Bluetooth_Headset_Battery_Level#74]
Hello,

I've already installed everything but it gives me this error:

```
Traceback (most recent call last):
  File "/home/manel/Documentos/bluetooth_battery.py", line 166, in <module>
    main()
  File "/home/manel/Documentos/bluetooth_battery.py", line 163, in main
    print("Battery level for {} is {}".format(device, str(query)))
  File "/home/manel/Documentos/bluetooth_battery.py", line 93, in __str__
    return "{:.0%}".format(self._perform_query() / 100)
  File "/home/manel/Documentos/bluetooth_battery.py", line 101, in _perform_query
    sock.connect(self._bt_settings)
  File "<string>", line 5, in connect
bluetooth.btcommon.BluetoothError: [Errno 111] Connection refused
```

**Comment by jrom99** [comment]
Can you provide more information about your device (make and model)? Also if it's mentioned in the output of `upower -d` and whether you can see its battery levels in other devices (phone, Mac or Windows)

I have the same problem with an Edifier W800BT and it was due to it not reporting battery at all.

**Comment by meetdilip** [comment]
Almost the same  issue here
```
$ ./bluetooth_battery.py My_MAC_Addr.3
Traceback (most recent call last):
  File "<string>", line 3, in connect
_bluetooth.error: (111, 'Connection refused')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dilip/Downloads/Bluetooth_Headset_Battery_Level-master/./bluetooth_battery.py", line 166, in <module>
    main()
  File "/home/dilip/Downloads/Bluetooth_Headset_Battery_Level-master/./bluetooth_battery.py", line 163, in main
    print("Battery level for {} is {}".format(device, str(query)))
  File "/home/dilip/Downloads/Bluetooth_Headset_Battery_Level-master/./bluetooth_battery.py", line 93, in __str__
    return "{:.0%}".format(self._perform_query() / 100)
  File "/home/dilip/Downloads/Bluetooth_Headset_Battery_Level-master/./bluetooth_battery.py", line 101, in _perform_query
    sock.connect(self._bt_settings)
  File "<string>", line 5, in connect
bluetooth.btcommon.BluetoothError: [Errno 111] Connection refused
```

**Comment by peylight** [comment]
I have the same problem.
the output of `upower -d` doesn't show my bluetooth device.
However in my android phone it is showing the percentage of battery.

**Comment by peylight** [comment]
@jrom99 Thx, The problem has been solved after enabling  [experimental features in Bluez](https://wiki.archlinux.org/title/bluetooth#Enabling_experimental_features)
