### ISSUE TITLE
bluetooth.btcommon.BluetoothError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by HarshalRathore** [TheWeirdDev/Bluetooth_Headset_Battery_Level#76]
Installation is done with `yay -S python-bluetooth-battery` 

command run 
`bluetooth_battery $(bluetoothctl info | awk '/^Device/ {print $2}')`
and
`sudo bluetooth_battery $(bluetoothctl info | awk '/^Device/ {print $2}')`

Error received

```
Traceback (most recent call last):
  File "<string>", line 3, in connect
_bluetooth.error: (111, 'Connection refused')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bluetooth_battery", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/bluetooth_battery/bluetooth_battery.py", line 163, in main
    print("Battery level for {} is {}".format(device, str(query)))
  File "/usr/lib/python3.10/site-packages/bluetooth_battery/bluetooth_battery.py", line 93, in __str__
    return "{:.0%}".format(self._perform_query() / 100)
  File "/usr/lib/python3.10/site-packages/bluetooth_battery/bluetooth_battery.py", line 101, in _perform_query
    sock.connect(self._bt_settings)
  File "<string>", line 5, in connect
bluetooth.btcommon.BluetoothError: [Errno 111] Connection refused

```

**Comment by MadFlasheroo7** [comment]
Did u find any fixes?

**Comment by HarshalRathore** [comment]
@MadFlasheroo7 no I haven't yet, waiting for the author of the project to respond.

**Comment by TheWeirdDev** [comment]
This error could be caused by many reasons. Some devices are not supported by this script and some have issues. I need to have access to the specific device in order to debug and test.

You can try the workarounds mentioned in the readme file, maybe that fixes the issue.

**Comment by P3nguin-M** [comment]
Connection is opening and connecting: Under class SocketDataIterator return the received socket data is being held up. have tried different chunk sizes, etc. 
The AT commands are sending to the device using logcat I found:
01-30 11:32:36.776  1661  1661 I Telecom:SamsungGearCommand: sendSecBluetoothATCommand : DUAL,S****E

Any ideas why the socket is unable to receive data back?

**Comment by TheWeirdDev** [comment]
@P3nguin-M Good job with the debugging. Can you also sniff the commands using [this trick](https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/issues/16#issuecomment-626850818) and send me the capture file? Include your logcat as well.

**Comment by TheWeirdDev** [comment]
This script is written only with battery level in mind. The commands which are being sent to the device might be wrong, and the device stops answering back. You can add debug prints to the program to see what is being sent/received. You can also look for similar commands in the logcat that you found before, and update the code.

**Comment by P3nguin-M** [comment]
> This script is written only with battery level in mind. The commands which are being sent to the device might be wrong, and the device stops answering back. You can add debug prints to the program to see what is being sent/received. You can also look for similar commands in the logcat that you found before, and update the code.

I figured if i can get the bluetooth battery stuff working i can modify afterwards to send the AT commands i extracted from the device's firmware. 
Is there any other scripts that you know of that lets us do just that? Test AT commands without modifying yours? Also notice you don't use any "at+" commands but just the endings. How does that work?

**Comment by MadFlasheroo7** [comment]
> This error could be caused by many reasons. Some devices are not supported by this script and some have issues. I need to have access to the specific device in order to debug and test.
> 
> You can try the workarounds mentioned in the readme file, maybe that fixes the issue.

how can i contribute add support for my devices

**Comment by TheWeirdDev** [comment]
@MadFlasheroo7 By capturing the Bluetooth connection from your phone and the headset, then analyzing the commands being sent/received. Then you can change code in order to support your device. It needs a lot of debugging and trial and error to get things working, plus there is no guarantee that it will work.

**Comment by P3nguin-M** [comment]
What mode is this bluetooth device supposed to be in? When i issue MAC.2 -> "Connected for calls" is shown. 
MAC.4 -> "Connected (Selected) Message Access". When i try MAC.3 -> Connecting then fails and reset by peer. 
MAC.2 & MAC.4 both stay connected but do not output any data from socket. I am now finding out the AT commands are going through while im on one of those modes 2/4. btsnoop log pasted below
[btsnoop_hci.log](https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/files/8025582/btsnoop_hci.log)

**Comment by TheWeirdDev** [comment]
> What mode is this bluetooth device supposed to be in? 

For Bluetooth headsets, we'll use the RFCOMM uuid to get the desired port number. Perhaps you can use the UUIDs that you have to find the port that suits your needs.

**Comment by MadFlasheroo7** [comment]
> @MadFlasheroo7 By capturing the Bluetooth connection from your phone and the headset, then analyzing the commands being sent/received. Then you can change code in order to support your device. It needs a lot of debugging and trial and error to get things working, plus there is no guarantee that it will work.

Should my android device be rooted? And kindly tell the process to log commands too

**Comment by TheWeirdDev** [comment]
> Should my android device be rooted? And kindly tell the process to log commands too

No I don't think so. You can check [this comment](https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/issues/16#issuecomment-626850818) for more info.

**Comment by asandikci** [comment]
interestingly, 
$ sudo apt-get install bluez* 
solved my problem

**Comment by carlocastoldi** [comment]
@TheWeirdDev I don't know if it's the right place where to post this, but I experience `Errno 111` as well with my BT dongle. I thus created the file log with Android: [btsnoop_hci.log](https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/files/8323790/btsnoop_hci.log)

If you can't fix it yourself, can you guide me on how to do it myself? Thanks in advance!

>   @MadFlasheroo7: Should my android device be rooted? And kindly tell the process to log commands too

in my experience you have to. On my Android 11 it got saved in `/data/misc/bluetooth/logs/`, not in sdcard

**Comment by MadFlasheroo7** [comment]
> @TheWeirdDev I don't know if it's the right place where to post this, but I experience `Errno 111` as well with my BT dongle. I thus created the file log with Android: [btsnoop_hci.log](https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/files/8323790/btsnoop_hci.log)
> 
> If you can't fix it yourself, can you guide me on how to do it myself? Thanks in advance!
> 
> > @MadFlasheroo7: Should my android device be rooted? And kindly tell the process to log commands too
> 
> in my experience you have to. On my Android 11 it got saved in `/data/misc/bluetooth/logs/`, not in sdcard

i actually got busy with my college stuff so once i root my device ill let u know

**Comment by ask-compu** [comment]
i have a Soundcore Anker Life Q20
i get this error on all but a few ports (tested 1 through 30, waiting a few seconds between tries)
ports 13,18: when specifying these ports the script seems to just hang
port 19 (and when not specifying any port): i get bluetooth.btcommon.BluetoothError: [Errno 16] Device or resource busy
